### ISSUE TITLE
Monthly Meeting Reminder

### ISSUE THREAD

**Issue by jrbourbeau** [dask/community#21]
As a reminder, the Dask monthly meeting is this Thursday.
 
**NOTE: the meeting has moved to Zoom (https://zoom.us/j/802251830) to accommodate the larger turnout we've had recently** : )

Details:

- Notes for where and when are available here: https://docs.dask.org/en/latest/support.html#discussion
- Meeting notes are available here: https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit

If people would like to discuss something I encourage them to put an item on the agenda (we can also do this during the meeting)

**Comment by TomAugspurger** [comment]
Make sure to verify your local time on the calendar. The US just had a
daylight savings transition.

**Comment by mrocklin** [comment]
I think that most European countries have also gone through the transition
(they were a week ahead of us), so at least in those two regions I think
that we should be aligned.

**Comment by pentschev** [comment]
Can we update the [calendar invite](https://calendar.google.com/event?action=TEMPLATE&tmeid=NmxnamVvcGtjY3E2NGI5bTZzcW1hYjlrYzhybTZiYjFjY29qOGI5ZzY0cWoyYzFrNjFpMzhwaGlja18yMDE5MDYwNlQxNjAwMDBaIDRsMHZ0czBjMWNnZGJxNWpoY29najU1c2ZzQGc&tmsrc=4l0vts0c1cgdbq5jhcogj55sfs%40group.calendar.google.com&scp=ALL) as referred in the [Community section](https://docs.dask.org/en/latest/support.html) with the correct link too?

**Comment by TomAugspurger** [comment]
Done, thanks.

**Comment by pentschev** [comment]
Hmm, I don't know why but for me the invite still has the old link (https://appear.in/dask-dev), I even deleted it and tried to add again. Is this just me or do others also see the old one instead of https://zoom.us/j/802251830?

**Comment by jrbourbeau** [comment]
For me the location has been updated to zoom, but the description has the appear.in link

<img width="438" alt="Screen Shot 2019-11-06 at 8 55 37 AM" src="https://user-images.githubusercontent.com/11656932/68308927-46f63100-0073-11ea-8d0f-a89ac92450ec.png">

**Comment by pentschev** [comment]
To me, both still show the old link:

![Screenshot 2019-11-06 at 16 02 31](https://user-images.githubusercontent.com/4398246/68309596-f56b9780-00ae-11ea-9a64-1798a4ac1329.png)

**Comment by pentschev** [comment]
To me both still show the old link:

![Screenshot 2019-11-06 at 16 02 31](https://user-images.githubusercontent.com/4398246/68310016-9d816080-00af-11ea-91d9-f0d3f6443ad0.png)

**Comment by TomAugspurger** [comment]
Perhaps check again in a bit. Apparently I didn't save the change earlier.

**Comment by pentschev** [comment]
I still see the old link, I also tried a different account and see the old both in description and location.

**Comment by jakirkham** [comment]
Yeah I had a bunch of old Dask monthly meeting events (one of which was on Wednesday and two today). Tried deleting all of them and readding the event, but am also seeing the event is not updated either.

**Comment by pentschev** [comment]
@jakirkham there's a PR to fix this in https://github.com/dask/dask/pull/5569 by @TomAugspurger. Perhaps we can close this issue (given that the meeting has passed already) and continue the discussion there?
